### ISSUE TITLE
[Bug] Destroyer - lost blocks

### ISSUE THREAD

**Issue by Tetrajak** [Lemonszz/Anima-Mundi#1]
If the Destroyer is in the process of breaking a block, and the world is unloaded, the block it is breaking is lost.

**Comment by Lemonszz** [comment]
I can't seem to replicate this.

Is the destroyer linked to any other node? If not, the item would still be inside the destroyer. 
If it is linked, are you sure that the item isn't inside another node?

If you can't find the item anywhere:

Singleplayer or Multiplayer? 
What block were you breaking?
What other node is destroyer connected to?

Thanks.

**Comment by Tetrajak** [comment]
Singleplayer.
Various, but I remember granite being one of them.
The destroyer is linked to an inserter, which is inputting into a chest so I can count the items.

**Comment by Lemonszz** [comment]
Is this a consistent thing or only happening some of the time?

**Comment by Tetrajak** [comment]
I've been able to reproduce it by exiting the world in single player. I'll test it again tonight to make sure I'm not miscounting.

**Comment by Tetrajak** [comment]
Sorry for the late follow up. I've been unable to reproduce the supposedly disappearing blocks. I was probably miscounting.

Anyway, I'm really liking what you've made so far, and have yet to break it, but I'll keep trying! Once 1.12 forge is stable, Anima Mundi is a strong candidate for my modded SSP instance.
