### ISSUE TITLE
[Suggestion] Add a "default route" to the sorter.

### ISSUE THREAD

**Issue by jojotastic777** [Lemonszz/Anima-Mundi#4]
As of right now, when using the sorter you have to set every item that you want sorted, and the sorter will jam if you give it too many unsorted items. Adding a "default route" to the sorter would both solve this problem, and allow chaining of multiple sorters, so you can sort more items to more destinations than a single sorter would allow.

**Comment by Lemonszz** [comment]
http://lemons.party/i/x1i6f.png

Done, will be in the next release.
