### ISSUE TITLE
Crash when linking Inserter to machines

### ISSUE THREAD

**Issue by Juuxel** [Lemonszz/Anima-Mundi#7]
The game crashes when linking an inserter to various machines (tested with Tech Reborn's Grinder and Actually Additions's Crusher).

Tested with clean instances of
- Minecraft 1.12
- Forge 14.21.1.2387
- Anima Mundi 0.1.0

with 
- RebornCore 1.12-3.2.3.83 
- Tech Reborn 1.12-2.6.6.151

or 
- Actually Additions 1.12-r113.

Game logs:
- [With Tech Reborn](https://gist.github.com/Juuxel/478fe907f3a5cf44bafed9f9e73094b0)
- [With Actually Additions](https://gist.github.com/Juuxel/3c71c4226b26c7bae374f69f50dc2a41)

`TileEntityLinkableWorker.sendEnergyToNode` is trying to cast other mods' energy storages to `IAnimaStorage` when linking the inserter, which seems to cause the crash.

**Comment by Lemonszz** [comment]
Oops, I'm away for a few days and won't be able to fix it right now. 

Thanks for bringing this to my attention, will get a fix out as soon as I'm back.
