### ISSUE TITLE
Issue with the Block Sucker

### ISSUE THREAD

**Issue by g-ooden** [Lemonszz/Anima-Mundi#9]
Using forge 14.21.1.2406 and the Anima Mundi version 1.12-0.2.0
I have some others mods listed in the [pastebin](https://pastebin.com/nHV4yb8F).

https://pastebin.com/nHV4yb8F

Encountered this when using the Destroyer on a block in my single player world.
The block becomes an entity for a split moment before the client shows the Shutting Down Internal Server screen.
The content in the pastebin was from my latest.log file rather than just the crash report.

Hope you can find a way to resolve the issue and I hope you know that you are doing a great job with the mod, and I can't wait to see where it's headed.
Thanks!

**Comment by Lemonszz** [comment]
Thanks for the report, this has been fixed and a new build has been uploaded.
